# Generated by Django 5.1.2 on 2024-11-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('DOB', models.TextField()),
                ('DOR', models.TextField()),
                ('SNumber', models.IntegerField()),
                ('SName', models.TextField()),
                ('ApartN', models.TextField()),
                ('ResZip', models.IntegerField()),
                ('Affiliation', models.CharField(max_length=1)),
                ('PNumber', models.IntegerField()),
                ('v20state', models.BooleanField()),
                ('v21town', models.BooleanField()),
                ('v21primary', models.BooleanField()),
                ('v22general', models.BooleanField()),
                ('v23town', models.BooleanField()),
                ('VoterS', models.IntegerField()),
            ],
        ),
    ]
