# Generated by Django 5.1.1 on 2024-10-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0002_statusmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmessage',
            name='TimeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
